### ISSUE TITLE
StructError on running npm start

### ISSUE THREAD

**Issue by PatrickAlphaC** [solana-labs/example-helloworld#131]
When running `npm run start`, I run into this error:

```
> ts-node src/client/main.ts

Let's say hello to a Solana account...
Error: 
    at new StructError (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/superstruct/src/struct-error.ts:37:18)
    at Function.assert (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/superstruct/src/struct.ts:55:13)
    at GetVersionRpcResult (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/superstruct/src/struct.ts:31:46)
    at Connection._callee38$ (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/@solana/web3.js/src/connection.js:2519:17)
    at tryCatch (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/patrick/code/solana-chainlink/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  type: 'pick<{solana-core,feature-set}>',
  value: undefined,
  path: [ 'result' ],
  branch: [
    {
      jsonrpc: '2.0',
      id: '357a4b49-f721-4c2a-88ef-7d2a24dcc60e',
      error: [Object]
    },
    undefined
  ],
  failures: [
    {
      value: undefined,
      branch: [Array],
      path: [Array],
      type: 'pick<{solana-core,feature-set}>'
    }
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! helloworld@0.0.1 start: `ts-node src/client/main.ts`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrick/.npm/_logs/2021-01-12T12_09_32_269Z-debug.log
```

When running `npm run localnet:logs` I get to this point in the logs: 
```
+ trap abort INT TERM EXIT
+ faucet=46
+ args=(--identity "$dataDir"/validator-identity.json --vote-account "$dataDir"/validator-vote-account.json --ledger "$ledgerDir" --gossip-port 8001 --rpc-port 8899 --rpc-faucet-address 127.0.0.1:9900 --log - --enable-rpc-exit --enable-rpc-transaction-history --init-complete-file "$dataDir"/init-completed --require-tower)
+ solana-faucet --keypair /usr/bin/config/solana-run/faucet.json
+ validator=47
+ wait 47
+ solana-validator --identity /usr/bin/config/solana-run/validator-identity.json --vote-account /usr/bin/config/solana-run/validator-vote-account.json --ledger /usr/bin/config/ledger --gossip-port 8001 --rpc-port 8899 --rpc-faucet-address 127.0.0.1:9900 --log - --enable-rpc-exit --enable-rpc-transaction-history --init-complete-file /usr/bin/config/solana-run/init-completed --require-tower
```

I have the local cluster up (I can see the container in `docker ps`), `npm run build:program-rust` looksl like it was successful, docker has 8 GB of memory and 3 GB of swap, I'm not sure where the program log is though.

OS: MacOS BigSur v11.1
Node: 12.20.0, v14.15.2, v10.23.0
npm: v6.14.9, v6.14.8
rustc: 1.49.0
solana-cli: 1.5.2 
docker: 20.10.2

**Comment by jackcmay** [comment]
Hi @PatrickAlphaC,  

Did you do the following steps?

`npm install`
`npm run localnet:down`
`npm run localnet:update`
`npm run localnet:up`
`npm run custer:localnet`
`npm run build:program-rust`
`npm run start`

I haven't updated to BigSur yet, so maybe...

**Comment by PatrickAlphaC** [comment]
@jackcmay yes

**Comment by jstarry** [comment]
I've seen this issue before and it has been fixed in a later version of web3.js which is updated as of https://github.com/solana-labs/example-helloworld/pull/173
