### ISSUE TITLE
thread panic on `solana-test-validator --log`

### ISSUE THREAD

**Issue by krotera** [solana-labs/example-helloworld#141]
When doing [this part of the quick start](https://github.com/solana-labs/example-helloworld#start-local-solana-cluster), I get:
```
$ solana-test-validator --log                                                                                                                    
[2021-01-27T16:24:31.000372750Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:31.000419678Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
[2021-01-27T16:24:31.405176680Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:31.405257191Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
[2021-01-27T16:24:31.810215933Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:31.810286525Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
[2021-01-27T16:24:32.215071070Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:32.215129459Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
[2021-01-27T16:24:32.619923250Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:32.619975739Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
[2021-01-27T16:24:33.025636930Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:33.025678298Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', faucet/src/faucet.rs:299:58
stack backtrace:                                                                                                                                                                    
[2021-01-27T16:24:33.429596895Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 invoke [1]
[2021-01-27T16:24:33.429649894Z DEBUG solana_runtime::message_processor] Program Vote111111111111111111111111111111111111111 success
   0: rust_begin_unwind            
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on                                                   
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'run faucet: RecvError', validator/src/bin/solana-test-validator.rs:312:25  
stack backtrace:                                                                          
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt                                                          
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: solana_test_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This still generates a `test-ledger` folder but apparently blocks the next step, `npm run build:program-rust`, which can't find a `package.json` in that folder. I also ran `npm install` to no effect.

**Comment by krotera** [comment]
A program was running on port 9900:
```
$ lsof -i :9900
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
SVPManage 2076  qio   31u  IPv6  37102      0t0  TCP *:iua (LISTEN)
```
Closing it and retrying fixes panic.
