### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by kornatisOiga** [solana-labs/example-helloworld#207]
This is the result of running the hello world in Gitpod versión

`$ npm run start
`
> helloworld@0.0.1 start
> ts-node src/client/main.ts

Let's say hello to a Solana account...
Failed to read RPC url from CLI config file, falling back to localhost
FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899
    at ClientRequest.<anonymous> (/workspace/example-helloworld/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}

**Comment by jstarry** [comment]
This means that the local validator is not running. You can run `solana-test-validator` in a separate terminal pane to fix this issue
