### ISSUE TITLE
Gitpod cold start fails

### ISSUE THREAD

**Issue by duncancarroll** [solana-labs/example-helloworld#215]
Hey folks!  Awesome Gitpod integration but it's breaking slightly:

(Duplicate of #207)

## Repro
Gitpod cold start + `npm run start` results in:

```
🤙 This task ran as a workspace prebuild
🎉 Well done on saving 1 minute

PATH=/home/gitpod/.local/share/solana/install/active_release/bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.rvm/gems/ruby-2.6.6/bin:/home/gitpod/.rvm/gems/ruby-2.6.6@global/bin:/home/gitpod/.rvm/rubies/ruby-2.6.6/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/ide/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.nvm/versions/node/v14.16.1/bin:/home/gitpod/.cargo/bin:/home/gitpod/.rvm/bin
Bad status code: 404: Not found.
bash: solana-keygen: command not found
bash: solana: command not found
bash: solana: command not found
gitpod /workspace/example-helloworld $ npm run start

> helloworld@0.0.1 start /workspace/example-helloworld
> ts-node src/client/main.ts

Let's say hello to a Solana account...
Failed to read RPC url from CLI config file, falling back to localhost
FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899
    at ClientRequest.<anonymous> (/workspace/example-helloworld/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! helloworld@0.0.1 start: `ts-node src/client/main.ts`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-05-19T17_50_46_517Z-debug.log
```

## Workaround
It's possible the root issue is just that the PATH export failed, but I had to execute the following commands (which are not in README-gitpod.md) before I could run the example:
`$ PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"`
`$ solana-keygen new`
`$ solana-test-validator`
(Open new bash window)
`$ solana program deploy dist/program/helloworld.so`
`$ npm run start`

**Comment by jstarry** [comment]
Fixed by https://github.com/solana-labs/example-helloworld/pull/221

**Comment by giantelk** [comment]
I'm getting a similar error, running the GitPod HelloWorld demo, right out of the box:

```
gitpod /workspace/example-helloworld $ npm run start

> helloworld@0.0.1 start /workspace/example-helloworld
> ts-node src/client/main.ts

Let's say hello to a Solana account...
Failed to read RPC url from CLI config file, falling back to localhost
FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899
    at ClientRequest.<anonymous> (/workspace/example-helloworld/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:375:28)
    at ClientRequest.emit (domain.js:470:12)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! helloworld@0.0.1 start: `ts-node src/client/main.ts`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-08-15T21_39_32_474Z-debug.log
gitpod /workspace/example-helloworld $ solana logs
bash: solana: command not found
```
