### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by davidspies** [solana-labs/example-helloworld#265]
When following the instructions in the README, I get:

```
$ npm run start
...
Error: Failed to read program keypair at '/home/david/projects/example-helloworld/dist/program/helloworld-keypair.json' due to error: TextEncoder is not defined. Program may need to be deployed with `solana program deploy dist/program/helloworld.so`
    at Object.<anonymous> (/home/david/projects/example-helloworld/src/client/hello_world.ts:153:11)
    at Generator.throw (<anonymous>)
    at rejected (/home/david/projects/example-helloworld/src/client/hello_world.ts:27:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! helloworld@0.0.1 start: `ts-node src/client/main.ts`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2021-08-03T23_01_53_539Z-debug.log
```

**Comment by jstarry** [comment]
Which version of `node` are you using? We recommend v14 or later

**Comment by davidspies** [comment]
Thanks
Upgrading fixed it (I was on v10 something)
