### ISSUE TITLE
Unexpected token on 22.04

### ISSUE THREAD

**Issue by amm2901** [solana-labs/example-helloworld#493]
When I go to run the program with npm run start after deploying the on chain I get this error, and I have no idea why. I never mad any changes to the given files from the clone.

if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/workspace/example-helloworld/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

SAME ERROR ON 20.04.04

**Comment by swaroopmaddu** [comment]
I think it's related to node version.Please upgrade your node to new version and try again. @amm2901

**Comment by sohrabious** [comment]
i am getting the same error and my node is up to date,i could run the same program in other systems easily and with first try

**Comment by swaroopmaddu** [comment]
What's the node version you are on? Can you send the output of `node --version`

**Comment by amm2901** [comment]
I had to manually update using NodeSource since the terminal thought it was up to date. I am now on 16.15.1. It runs perfectly with an warning flag for dependencies but if you then run "$ npm rebuild" and run again it is a perfect output and run.

**Comment by sohrabious** [comment]
v12.22.9
 this is the version of my node

**Comment by sohrabious** [comment]
the problem was the version of my node
thank you very much <3
i've been struglling with the problem for a week :D

**Comment by swaroopmaddu** [comment]
Yeah it's because of outdated node version @amm2901 @sohrabious
