### ISSUE TITLE
npm install: failed to parse Cargo.lock

### ISSUE THREAD

**Issue by holoneo** [solana-labs/example-helloworld#57]
When I run `npm install` I get the following error. Any ideas how to fix it?

### Console Output

```
Cleaning /home/user/dev/blockchain/solana/example-helloworld/src/program-rust

> helloworld@0.0.1 clean:store /home/user/dev/blockchain/solana/example-helloworld
> rm -rf store

error: failed to parse lock file at: /home/user/dev/blockchain/solana/example-helloworld/src/program-rust/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! helloworld@0.0.1 postinstall: `npm run bpf-sdk:update && cargo update --manifest-path=src/program-rust/Cargo.toml`
npm ERR! Exit status 101
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-08-04T11_02_02_349Z-debug.log
```
### Log File

```
32968 verbose lifecycle helloworld@0.0.1~postinstall: CWD: /home/user/dev/blockchain/solana/example-helloworld
32969 silly lifecycle helloworld@0.0.1~postinstall: Args: [
32969 silly lifecycle   '-c',
32969 silly lifecycle   'npm run bpf-sdk:update && cargo update --manifest-path=src/program-rust/Cargo.toml'
32969 silly lifecycle ]
32970 silly lifecycle helloworld@0.0.1~postinstall: Returned: code: 101  signal: null
32971 info lifecycle helloworld@0.0.1~postinstall: Failed to exec postinstall script
32972 verbose stack Error: helloworld@0.0.1 postinstall: `npm run bpf-sdk:update && cargo update --manifest-path=src/program-rust/Cargo.toml`
32972 verbose stack Exit status 101
32972 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
32972 verbose stack     at EventEmitter.emit (events.js:311:20)
32972 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
32972 verbose stack     at ChildProcess.emit (events.js:311:20)
32972 verbose stack     at maybeClose (internal/child_process.js:1021:16)
32972 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
32973 verbose pkgid helloworld@0.0.1
32974 verbose cwd /home/user/dev/blockchain/solana/example-helloworld
32975 verbose Linux 5.4.0-42-generic
32976 verbose argv "/home/user/.nvm/versions/node/v12.16.1/bin/node" "/home/user/.nvm/versions/node/v12.16.1/bin/npm" "install"
32977 verbose node v12.16.1
32978 verbose npm  v6.13.4
32979 error code ELIFECYCLE
32980 error errno 101
32981 error helloworld@0.0.1 postinstall: `npm run bpf-sdk:update && cargo update --manifest-path=src/program-rust/Cargo.toml`
32981 error Exit status 101
32982 error Failed at the helloworld@0.0.1 postinstall script.
32982 error This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment

- Ubuntu 20
- node v12.16.1
- npm 6.13.4
- Docker version 19.03.12
- Wget 1.20.3
- rustup 1.18.1
- rustc 1.34.1
- cargo 1.34.0

**Comment by holoneo** [comment]
Issue solved by updating my cargo and rustc using `rustup update`
