### ISSUE TITLE
BpfLoader.load sometimes fails 

### ISSUE THREAD

**Issue by prographo** [solana-labs/example-helloworld#9]
BpfLoader.load sometimes fails, sometimes succeeds, with the same program, on TDS.

Recreate like this:

Clone the repo, make no changes to the SC program.

Set CLUSTER to testnet, LIVE=1, and make your environment point to TDS, and fund your id.json account with TDS coins.

Edit /client/hello_world.js change the loadProgram function to do the load with your id.json account then quit.

```
export async function loadProgram(): Promise<void> {

  const secret = JSON.parse( await fs.readFile( '/Users/mrsmith/.config/solana/id.json' ))
  const account = new Account( secret )
  console.log( `Balance of ${account.publicKey} is ${await connection.getBalance( account.publicKey )}` )

[...]

  //const bpf_payer = await newAccountWithLamports(connection, cost);
  const bpf_payer = account
  
  // Load the program
  console.log('Loading hello world program...');
  programId = await BpfLoader.load(connection, bpf_payer, data);
  console.log('Program loaded to account', programId.toBase58());

  process.exit(0)
```

Repeatedly execute the program - which will typically succeed in the load - until it fails:

```
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 2058561600
SMITH LOAD: /Users/mrsmith/SOLANA/example-helloworld/store/config.json
Loading hello world program...
Program loaded to account ASg8CZn8tKBLQ7xZDPYXhCx3E6gN8AzhVtVVZnLXSE6t
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 1940876800
SMITH LOAD: /Users/mrsmith/SOLANA/example-helloworld/store/config.json
Loading hello world program...
Error: Transaction 2EQbPzz3H9yU3MhhSEqEpURgH9HoDuWcCc3aTzmvxKb6Xju9s4Yi6eWqgeaq8o48XVgiKaVLbahoaSurBgNsFjug failed ({"slot":7829168,"confirmations":0,"err":{"InstructionError":[0,"InvalidAccountData"]}})
    at _callee3$ (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.js:79:15)
    at tryCatch (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

Env

```
~/SOLANA/example-helloworld/src/client$ uname -a
Darwin Mrs-MacBook-Pro 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
~/SOLANA/example-helloworld/src/client$ solana --version
solana-cli 1.1.2
~/SOLANA/example-helloworld/src/client$ npm --version
6.11.3
~/SOLANA/example-helloworld/src/client$ node --version
v12.12.0
```

**Comment by jackcmay** [comment]
@prographo 
When you see the load fail does it always fail after that?

How many times do you see it succeed until it fails?  Is it consistent?

**Comment by prographo** [comment]
That error *is* the load failing I believe... I don't see a pattern, you can see below, it failed second time, then worked many times, before failing again.
```
~/SOLANA/example-helloworld/src/client$ vi hello_world.js 
~/SOLANA/example-helloworld/src/client$ rm /Users/mrsmith/SOLANA/example-helloworld/store/config.json
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 1468275160
Loading hello world program...
Program loaded to account BCmfwGCJXkoGAYi53HRhvpeWJq5F6rMQcfTwxKWSi65D
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 1350590360
Loading hello world program...
Error: Transaction 5PJdow3jViwdfSos79D5dDaxEWeEFci2EnqRpuPihgQ8ozWAwa1ZRTjacZTPYgQoDkWT65ZCBa4VTECMAYxCL6PN failed ({"slot":7875468,"confirmations":0,"err":{"InstructionError":[0,"InvalidAccountData"]}})
    at _callee3$ (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.js:79:15)
    at tryCatch (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 1232945560
Loading hello world program...
Program loaded to account HMJiSzEx4MCRH7i6AsyDEVRpdkLDDRkKW8fk7McpvKKm
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 1115260760
Loading hello world program...
Program loaded to account Dy5kMvmzQtjyRZgANaDe42LQD14iatnzHRa2FMo8hvDb
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 997575960
Loading hello world program...
Program loaded to account HovfB5kbdjgVPwiie9TT9PfCBVxczoPgM9KzqegL1JkS
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 879861160
Loading hello world program...
Program loaded to account 3q34FMdADXxpqRoit13wqb7LPTTPYEcxFDFT3dHfGNuF
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 762176360
Loading hello world program...
Program loaded to account 8pRFzd587JQMuu54ig35yzM3SkNwRx4FKwfQtbPn3RCL
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 644491560
Loading hello world program...
Program loaded to account EBmxeir3YVpRTNAG2Wy3PS4EbZg6jeAv1qxgyG5AGNwx
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 526806760
Loading hello world program...
Program loaded to account 9vpzxmYTKB2BqhgnPcqm5FVZta4kbVBCNkf87CTqMD6a
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 409121960
Loading hello world program...
Program loaded to account 2bbJzNWbT1dw4gJs2SJ89GnQ4DFtipL4CFqBJ5gSvFGe
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 291437160
Loading hello world program...
Program loaded to account HdgLM3MjimyNCQAubJbEDMQFExKPfCLusKM81JnYAVwB
~/SOLANA/example-helloworld/src/client$ 
~/SOLANA/example-helloworld/src/client$ npm run start

> helloworld@0.0.1 start /Users/mrsmith/SOLANA/example-helloworld
> babel-node src/client/main.js

Let's say hello to a Solana account...
Connection to cluster established: http://testnet.solana.com { 'solana-core': '1.1.2' }
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 173752360
Loading hello world program...
Error: Transaction 5ay1mq7VYvbFppZTy6X7tQ2ve4ntRurwsA9GWmZiqUVs8YL7a1VzDsaywUkV4efssZ8H9ybqguBHHHGZ7XqZYnUw failed ({"slot":7876082,"confirmations":0,"err":{"InstructionError":[0,"AccountDataTooSmall"]}})
    at _callee3$ (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.js:79:15)
    at tryCatch (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/mrsmith/SOLANA/example-helloworld/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/mrsmith/SOLANA/example-helloworld/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jackcmay** [comment]
Interesting, thanks for the info! looking into it

**Comment by prographo** [comment]
I edited the above -- the final fail was due to me running out of coins. I will try some more and see if I can establish the pattern.

**Comment by prographo** [comment]
Ok, I put it on an infinite loop and removed the cruft output...

Can you recreate this, because if not, then probably I have done something stupid. This is a very real possibility.

I noticed errors vary; InvalidAccountData, AccountDataTooSmall, IncorrectProgramId.

If you can reproduce, then it's real... I'm thinking, can we determine who the leader is when it fails, because it might be down to that, right? Is that possible?


```
~/SOLANA/example-helloworld$ while [ 1 ]; do date ; npm run start 2>&1 | egrep '(loaded|Error|Balance)'; done
Thu  9 Apr 2020 18:28:33 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 7232752360
Error: Transaction 5jPQpuUuUf9mbp5TQ53pDwBpz36PcSC3jns4nYa674Q1upJFiCrBxjDkdGc6vV4kjDcJznq9xzvBpuVWqbn4He7h failed ({"slot":7879637,"confirmations":0,"err":{"InstructionError":[0,"AccountDataTooSmall"]}})
Thu  9 Apr 2020 18:28:42 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 7232752360
Program loaded to account CWmya8M7iuoothWhGSSZH9WVZCAXs4KLigCQQzkBVefs
Thu  9 Apr 2020 18:28:59 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 7115027560
Error: Transaction 9cbDnCdib6nfRJmaG9khVGCQW6NnDYtGJhkGJKKpL8xcqLYecRiTq4DxKPHbrPWjYZS2dcMVzv7Tn99owTWxCs3 failed ({"slot":7879692,"confirmations":0,"err":{"InstructionError":[0,"AccountDataTooSmall"]}})
Thu  9 Apr 2020 18:29:05 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 7114977560
Program loaded to account 9f9BgKAWyTJfyG3ZfVws6gY4Q25iSC4RcyAXbDN5GGDd
Thu  9 Apr 2020 18:29:18 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6997292760
Program loaded to account 8bt3GC7Hy5MmbBpYBsDenyCtz8CSKVXZHYtoQ4jhFyke
Thu  9 Apr 2020 18:29:35 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6879607960
Program loaded to account CH6B34rgtax2nAj6mpJXxJorBLZBCmeWny8XuoiP2iFc
Thu  9 Apr 2020 18:29:53 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6761923160
Program loaded to account AhC4T2s6zSg3SZemnk5d7dJxYFwhhPCFgqonLbjusLb1
Thu  9 Apr 2020 18:30:17 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6644238360
Program loaded to account DesGvyZ1KRTpoyT1ypQa44BDDWrKeem6wmtzzpiBaj4n
Thu  9 Apr 2020 18:30:38 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6526553560
Program loaded to account DXsu59Sf9PpnYoc8wdBQRHREJ8AU7DmQUFmCEVfProYE
Thu  9 Apr 2020 18:31:03 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6408868760
Program loaded to account GUiqHUEwYuHdfd3YUygAN7CywZE65ninCLazBDSXrFpc
Thu  9 Apr 2020 18:31:18 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6291183960
Program loaded to account 4GuyVc9P16ANUFGyYsSE1Ers9mwDg8iWDD4E7eJ7Skmm
Thu  9 Apr 2020 18:31:42 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6173499160
Program loaded to account 639Ky2WmjBHpJiVrFDu8a2Bd67vvtLra7zaJKwby3jsU
Thu  9 Apr 2020 18:32:14 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 6055814360
Program loaded to account ExcgpJH5MQNKNSE7oBVWBxpewPUowrwsmefE4hsfXmuH
Thu  9 Apr 2020 18:32:27 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5938129560
Program loaded to account DUxUM3GJfZJymM72sfcZ81aVqWujruYXh5Jbc7u8uTaJ
Thu  9 Apr 2020 18:32:57 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5820444760
Program loaded to account ErjmZeLULGSqorBtHQhUKVs5RaZADwQL9vT6UNtgndVY
Thu  9 Apr 2020 18:33:11 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5702759960
Program loaded to account TX5UXXroGQDxsBggi6UTJXa1de6JuKwTHBWCYVpBbid
Thu  9 Apr 2020 18:33:45 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5585075160
Program loaded to account 9dVtsGBXFpyS9yAKwwBiDGNm3xboeXNFKaRhfY8Pbekf
Thu  9 Apr 2020 18:34:01 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5467390360
Program loaded to account 61dDNa3AnEFZ999sh8pUq1dcjA9VohnDRJMUnFc1jfmq
Thu  9 Apr 2020 18:34:23 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5349705560
Program loaded to account GG8jkm5fx4hFhrz4nVs6KZaLAECBv9L8Yebmz3hBB6gP
Thu  9 Apr 2020 18:34:36 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5232020760
Program loaded to account 6DcKcDrWaupbx752Y5vtH9FBuzeKgfCGLtm2rcFnipun
Thu  9 Apr 2020 18:35:05 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 5114335960
Program loaded to account AwRqDuXVmRvBJMLmF3UbzMmfFKtx49m9MaFwRUPrgyrS
Thu  9 Apr 2020 18:35:26 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4996651160
Program loaded to account 8uf5ViYZywtYUvYqf1DKDcx7g91ZckbTywgonsT8m7kX
Thu  9 Apr 2020 18:35:41 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4878966360
Program loaded to account 6EseWxQUUkKGVTuuG4BMwGS2ekTRegUtg8t9iVouxacp
Thu  9 Apr 2020 18:36:03 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4761281560
Program loaded to account AkJoKJKa7LoEYehA9Yvt4DCWrB3AGS4LEQhxQZEPbVmJ
Thu  9 Apr 2020 18:36:18 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4643596760
Program loaded to account CoBfm8LKhdHZfPko5s34Udboo1KtNXGvtdifXMxYyYf4
Thu  9 Apr 2020 18:36:32 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4525911960
Program loaded to account GXVK35UzgmGmAiq5MY32GfBRXcL2q53D5xSrsqWS24wG
Thu  9 Apr 2020 18:37:08 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4408227160
Error: Transaction 2YnraGgXYQouZBNmN7TdLeUpif3cm13Q5h56kDES7BkePbF7zBhY2e1S5qtGsMRtV5knMyUHHK9brCbQtmgJsmPZ failed ({"slot":7880742,"confirmations":0,"err":{"InstructionError":[0,"InvalidAccountData"]}})
Thu  9 Apr 2020 18:37:31 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4290552360
Error: Transaction uxiSf7LdioqW8F2hBu8HJQ239MLLSUwq8NnKRLfyvtfdqwrdHmeWzVuc2wXQPrskn9fNuQFGFDg4vY7rxJTfq9B failed ({"slot":7880806,"confirmations":0,"err":{"InstructionError":[0,"IncorrectProgramId"]}})
Thu  9 Apr 2020 18:37:59 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4172837560
Program loaded to account 4XXZbBhevx1f5uXXCwbwNvohji6txNaffaYSXA8T2ycw
Thu  9 Apr 2020 18:38:20 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4055152760
Error: Transaction 5pwLQv8PgvgrHXxoa9vKQwpWEuf6EBnSBndFKcyhjjpDyW2XCXrKg376TWfBEGb8X1tz6NBELPUpetA9tFEAnEVW failed ({"slot":7880855,"confirmations":0,"err":{"InstructionError":[0,"AccountDataTooSmall"]}})
Thu  9 Apr 2020 18:38:25 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4055082760
Error: Transaction 4hWTuhkUQpQpkcxcYdELnjQNuXL4EB9do4Uvrhe9STcHEDFiMMVobpTCNELz26AhrbuSwLirGQo1csRv1PCrZqyi failed ({"slot":7880869,"confirmations":0,"err":{"InstructionError":[0,"AccountDataTooSmall"]}})
Thu  9 Apr 2020 18:38:32 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 4055002760
Program loaded to account 2D8CdJ59nrr9Nsz4VEpvLKSgZhug3DXEeEuktwfobpVC
Thu  9 Apr 2020 18:38:52 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 3937317960
Error: Transaction Md7Pgfos7uzy6r3XfGJxBka7DgSLi7x2ofNZDxg76MehDyzcC2oiiDyLHqhjT1hCuvUGYxHu2Wnaq2bP1ofPLyY failed ({"slot":7880928,"confirmations":0,"err":{"InstructionError":[0,"AccountDataTooSmall"]}})
Thu  9 Apr 2020 18:38:59 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 3937307960
Program loaded to account qtXnxEHyjtUjchKA3DQd7k45iVJapszfBbdYip5MdM9
Thu  9 Apr 2020 18:39:26 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 3819623160
Error: Transaction 4WYDDNDu5YvKAHVghQUnjv4ziwABMqfEejcJBnVt3mAqBtcAAnRocx53S2N2QMwpJqAvKL5r5BcJ34fBvz2X9MyB failed ({"slot":7881028,"confirmations":0,"err":{"InstructionError":[0,"InvalidAccountData"]}})
Thu  9 Apr 2020 18:39:43 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 3701958360
Error: Transaction mUqt7hTHNWpwTnn69cXF38LVqYxW6f7ynxqkcjsEARZEnoQDn9s5se31f2AE38pAZsWxupWZKM9SYA1YCk18qzd failed ({"slot":7881084,"confirmations":0,"err":{"InstructionError":[0,"InvalidAccountData"]}})
Thu  9 Apr 2020 18:40:11 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 3584313560
Program loaded to account AGRVTLdoutDt5Ds8bBP9Pe3ipUf7Ses591QS7eCjPQdp
Thu  9 Apr 2020 18:40:27 BST
Balance of FKfGiCuNXXFTr7E3GCYkN7fXCm6SgAohkgGb2JiPSa3e is 3466628760
Program loaded to account 6xb4QJV8emySG8BQELyPzC7RCJbcBmftzHUE5aJfcp5a
```

**Comment by jackcmay** [comment]
I'm thinking the same way @jstarry is and that we should probably be waiting for at least one confirmation.  I'll try and recreate and try out the confirmation change.

**Comment by jackcmay** [comment]
@prographo I was able to recreate the issue and the following PR should fix it:
https://github.com/solana-labs/solana-web3.js/pull/814
